#! groovy
node {
   stage 'Checkout'
        checkout scm

   stage 'Setup'
        sh 'cd helloworld'
        sh 'npm install'

   stage 'Mocha test'
        sh 'cd helloworld'
        sh './node_modules/mocha/bin/mocha'

   stage 'Cleanup'
        sh 'cd helloworld'
        echo 'prune and cleanup'
        sh 'npm prune'
        sh 'rm node_modules -rf'
}
